# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

# Style preferences
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

# Rails specific
Rails/ApplicationRecord:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/ReflectionClassName:
  Enabled: true

# Security
Security/MarshalLoad:
  Enabled: true

# Performance
Performance/RedundantMerge:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true
