# Configuration LCL/Sherlock
# Copiez ce fichier vers config/lcl.yml et remplissez avec vos vraies valeurs

development:
  merchant_id: "VOTRE_MERCHANT_ID_DEVELOPPEMENT"
  certificate_path: "config/certificates/lcl_dev.crt"
  private_key_path: "config/certificates/lcl_dev.key"

production:
  merchant_id: "VOTRE_MERCHANT_ID_PRODUCTION"
  certificate_path: "config/certificates/lcl_prod.crt"
  private_key_path: "config/certificates/lcl_prod.key"

# Instructions:
# 1. Créez le dossier config/certificates/
# 2. Placez-y vos certificats LCL
# 3. Ajoutez config/lcl.yml à votre .gitignore
# 4. Configurez les credentials Rails avec:
#    rails credentials:edit
#    Ajoutez:
#    lcl:
#      merchant_id: "VOTRE_MERCHANT_ID"
#      certificate_path: "config/certificates/lcl.crt"
#      private_key_path: "config/certificates/lcl.key"
